export const subcategoriesParameters = {
  'Acceso al mercado y relaciones institucionales': 'acceso-mercado-relaciones-institucionales',
  'Administraciones europeas': 'administraciones-europeas',
  Administración: 'administracion',
  'Administración autonómica': 'administracion-autonomica',
  'Administración de bases de datos': 'administracion-bases-datos',
  'Administración del Estado': 'administracion-estado',
  'Administración inmobiliaria': 'administracion-inmobiliaria',
  'Administración local': 'administracion-local',
  Aeronáutico: 'aeronautico',
  'Agente comercial': 'agente-comercial',
  'Agricultura y jardinería': 'agricultura-jardineria',
  'Agrónomo y montes': 'agronomo-montes',
  Almacén: 'almacen',
  Análisis: 'analisis',
  Arquitectura: 'arquitectura',
  'Arquitectura y proyección': 'arquitectura-proyeccion',
  'Artes interpretativas': 'artes-interpretativas',
  'Artes plásticas': 'artes-plasticas',
  Artesanía: 'artesania',
  'Asuntos regulatorios': 'asuntos-regulatorios',
  'Atención al cliente': 'atencion-a-cliente',
  Auditoría: 'auditoria',
  Automoción: 'automocion',
  'Banca empresarial': 'banca-empresarial',
  'Banca privada': 'banca-privada',
  'Bolsa, valores e inversión': 'bolsa-valores-inversion',
  Calidad: 'calidad',
  'Calidad, producción e I+D': 'calidad-producciï¿½n-i-d',
  Carpintería: 'carpinteria',
  'Certificación de calidad': 'certificacion-calidad',
  Comercial: 'comercial',
  'Comercial y ventas': 'comercial-ventas',
  'Comercio exterior': 'comercio-exterior',
  'Compras y aprovisionamiento': 'compras-aprovisionamiento',
  'Comunicación corporativa': 'comunicacion-corporativa',
  Confección: 'confeccion',
  Consultoría: 'consultoria',
  'Consumo y alimentación': 'consumo-alimentacion',
  'Creación audiovisual': 'creacion-audiovisual',
  'Cuerpos de seguridad': 'cuerpos-seguridad',
  'Derecho civil, penal y constitucional': 'derecho-civil-penal-constitucional',
  'Derecho internacional': 'derecho-internacional',
  'Derecho procesal': 'derecho-procesal',
  'Derecho y empresa': 'derecho-empresa',
  'Desarrollo de marca y producto': 'desarrollo-marca-producto',
  'Dirección y gerencia': 'direccion-gerencia',
  'Dirección y gestión de obras': 'direccion-gestion-obras',
  'Diseño gráfico': 'diseno-grafico',
  'Diseño industrial': 'diseno-industrial',
  'Diseño web': 'diseno-web',
  'Distribución y logística': 'distribucion-logistica',
  'ERP, CRM, Business Intelligence': 'erp-crm-business-intelligence',
  'Editorial e imprenta': 'editorial-imprenta',
  'Educación especial': 'educacion-especial',
  'Educación social': 'educacion-social',
  Electricidad: 'electricidad',
  Electrónica: 'electronica',
  'Electrónica y automática industrial': 'electronica-automatica-industrial',
  'Empresas públicas': 'empresas-publicas',
  'Energias Renovables': 'energias-renovables',
  Enfermería: 'enfermeria',
  Enseñanza: 'ensenanza',
  'Estética y cosmética': 'estetica-cosmetica',
  'Facturación, cobros y pagos': 'facturacion-cobros-pagos',
  Farmacia: 'farmacia',
  'Finanzas y contabilidad': 'finanzas-contabilidad',
  Fontanería: 'fontaneria',
  Formación: 'formacion',
  'Fotografía ': 'fotografia',
  'Geología, geodesia y cartografía': 'geologia-geodesia-cartografia',
  'Gestión de centros educativos': 'gestion-centros-educativos',
  'Gestión de la calidad': 'gestion-calidad',
  'Gestión de proyectos': 'it-gestion-proyectos',
  'Gran cuenta': 'gran-cuenta',
  'Hardware, redes y seguridad': 'hardware-redes-seguridad',
  Helpdesk: 'helpdesk',
  Hostelería: 'hosteleria',
  Industrial: 'industrial',
  'Ingeniería civil y obras públicas': 'ingenieria-civil-obras-publicas',
  'Ingeniería de materiales': 'ingenieria-materiales',
  Interiorismo: 'interiorismo',
  'Investigación clínica y asuntos médicos': 'investigacion-clinica-asuntos-medicos',
  'Investigación de mercados': 'investigacion-mercados',
  'Investigación y desarrollo': 'investigacion-desarrollo',
  Limpieza: 'limpieza',
  Mantenimiento: 'mantenimiento',
  Marketing: 'marketing',
  'Marketing y comunicación': 'marketing-comunicacion',
  'Medicina especializada': 'medicina-especializada',
  'Medicina general': 'medicina-general',
  'Medicinas alternativas': 'medicinas-alternativas',
  'Medio ambiente': 'medio-ambiente',
  Metrología: 'metrologia',
  Minas: 'minas',
  'Moda y confección': 'moda-confeccion',
  'Naval y oceánico': 'naval-oceanico',
  'Negociación y contratación': 'negociacion-contratacion',
  'Notaría y registros': 'notaria-registros',
  Odontología: 'odontologia',
  'Oficios de la construcción': 'oficios-construccion',
  Operaciones: 'operaciones',
  'Operaciones societarias': 'operaciones-societarias',
  'Organización de la empresa': 'organizacion-empresa',
  'Organización industrial': 'organizacion-industrial',
  'Otras ingenierías': 'otras-ingenierias',
  'Otras profesiones sanitarias': 'otras-profesiones-sanitarias',
  'Otros oficios': 'otros-oficios',
  Pedagogía: 'pedagogia',
  'Periodismo y edición': 'periodismo-edicion',
  'Prevención de riesgos': 'prevencion-riesgos',
  Producción: 'produccion',
  'Productos y servicios bancarios': 'productos-servicios-bancarios',
  Programación: 'programacion',
  'Promoción y ferias': 'promocion-ferias',
  Psicología: 'psicologia',
  Publicidad: 'publicidad',
  Puericultura: 'puericultura',
  Químico: 'quimico',
  'RRPP y eventos': 'rrpp-eventos',
  Recepción: 'recepcion',
  'Relaciones laborales': 'relaciones-laborales',
  Restauración: 'restauracion',
  Secretariado: 'secretariado',
  'Seguridad y vigilancia': 'seguridad-vigilancia',
  Seguros: 'seguros',
  'Selección de personal': 'seleccion-personal',
  'Sin especificar': '-',
  Sistemas: 'sistemas',
  'Sistemas de defensa': 'sistemas-defensa',
  Telecomunicaciones: 'telecomunicaciones',
  'Televenta y marketing telefónico': 'televenta-marketing-telefonico',
  'Traducción e interpretación': 'traduccion-interpretacion',
  Transporte: 'transporte',
  Turismo: 'turismo',
  'Técnicas audiovisuales': 'tecnicas-audiovisuales',
  'Venta al detalle': 'venta-detalle',
  Veterinaria: 'veterinaria'
}
export const experienceParameters = {
  0: 'no-requerida',
  1: 'al-menos-1-ano',
  2: 'al-menos-2-anos',
  3: 'al-menos-3-anos',
  4: 'al-menos-4-anos',
  5: 'mas-de-5-anos',
  10: 'mas-de-10-anos'
}
export const teleworkingParameters = {
  'Solo teletrabajo': 'solo-teletrabajo',
  Híbrido: 'teletrabajo-posible',
  'Sin especificar': 'no-se-sabe-no-esta-decidido',
  Presencial: 'trabajo-solo-presencial'
}

export const categoryParameters = {
  'Administración Pública': 'administracion-publica',
  'Administración de empresas': 'administracion-empresas',
  'Atención a clientes': 'atencion-a-cliente',
  'Calidad, producción e I+D': 'calidad-produccion-id',
  'Comercial y ventas': 'comercial-ventas',
  'Compras, logística y almacén': 'compras-logistica-almacen',
  'Diseño y artes gráficas': 'diseno-artes-graficas',
  'Educación y formación': 'educacion-formacion',
  'Finanzas y banca': 'finanzas-banca',
  'Informática y telecomunicaciones': 'informatica-telecomunicaciones',
  'Ingenieros y técnicos': 'ingenieros-tecnicos',
  'Inmobiliario y construcción': 'inmobiliario-construccion',
  Legal: 'legal',
  'Marketing y comunicación': 'marketing-comunicacion',
  'Profesiones, artes y oficios': 'profesiones-artes-oficios',
  'Recursos humanos': 'recursos-humanos',
  'Sanidad y salud': 'sanidad-salud',
  'Sector Farmacéutico': 'sector-farmaceutico',
  'Turismo y restauración': 'turismo-restauracion',
  'Ventas al detalle': 'ventas-detalle',
  Otros: 'otros'
}
